//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopBreakers.WebApp.Resources.DTOs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DTOs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DTOs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopBreakers.WebApp.Resources.DTOs.DTOs", typeof(DTOs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Środki na start :).
        /// </summary>
        public static string balanceForStart {
            get {
                return ResourceManager.GetString("balanceForStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string createdDate {
            get {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluta.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wyświetlana.
        /// </summary>
        public static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płeć.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer identyfikacyjny.
        /// </summary>
        public static string identityNumber {
            get {
                return ResourceManager.GetString("identityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer konta - IBAN [PL...].
        /// </summary>
        public static string newIban {
            get {
                return ResourceManager.GetString("newIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon [+48...].
        /// </summary>
        public static string newPhone {
            get {
                return ResourceManager.GetString("newPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię odbiorcy.
        /// </summary>
        public static string receiverFirstname {
            get {
                return ResourceManager.GetString("receiverFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko odbiorcy.
        /// </summary>
        public static string receiverLastname {
            get {
                return ResourceManager.GetString("receiverLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string reference {
            get {
                return ResourceManager.GetString("reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ transferu.
        /// </summary>
        public static string transferType {
            get {
                return ResourceManager.GetString("transferType", resourceCulture);
            }
        }
    }
}
