//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopBreakers.WebApp.Resources.Views.Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopBreakers.WebApp.Resources.Views.Report.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport aktywności.
        /// </summary>
        public static string activityReport {
            get {
                return ResourceManager.GetString("activityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyczyść.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki waluty.
        /// </summary>
        public static string currencyStats {
            get {
                return ResourceManager.GetString("currencyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szukaj od daty.
        /// </summary>
        public static string dateFrom {
            get {
                return ResourceManager.GetString("dateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik logowań.
        /// </summary>
        public static string loginsCounter {
            get {
                return ResourceManager.GetString("loginsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęstsze godziny transferów.
        /// </summary>
        public static string mostCommonTransferHrs {
            get {
                return ResourceManager.GetString("mostCommonTransferHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik rejestracji.
        /// </summary>
        public static string registerCounter {
            get {
                return ResourceManager.GetString("registerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szukaj.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prześlij raport.
        /// </summary>
        public static string transferReport {
            get {
                return ResourceManager.GetString("transferReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik transferów.
        /// </summary>
        public static string transfersCounter {
            get {
                return ResourceManager.GetString("transfersCounter", resourceCulture);
            }
        }
    }
}
